Import('RTT_ROOT')
from building import *

src	= Split("""
module/u-blox_LISA_U2XX.c
module/ublox_neo6.c
gps_data_parse.c
modem.c
utils.c
""")

CPPPATH = [GetCurrentDir()]
group = DefineGroup('Modem', src, depend = ['RT_USING_LWIP', 'RT_LWIP_PPP'], CPPPATH = CPPPATH)

Return('group')

