Import('RTT_ROOT')
Import('rtconfig')
from building import *

cwd     = GetCurrentDir()
src	 = Glob('*.c')
src	+= Glob('API_Lib/*.c')
CPPPATH = [cwd, cwd + '/API_Lib']

#use RT-Thread SPI interface.
SrcRemove(src, 'API_Lib/rsi_hal_mcu_spi.c')

#use RT-Thread timers.
SrcRemove(src, 'API_Lib/rsi_hal_mcu_timers.c')

group = DefineGroup('wifi_RS9110', src, depend = ['RT_USING_LWIP','RT_USING_RS9110'], CPPPATH = CPPPATH)

Return('group')
