from building import *

cwd = GetCurrentDir()
src = Glob('*.c')

# remove no need file.
if GetDepend('RT_USING_DEVICE') == False or GetDepend('RT_USING_SPI') == False:
	SrcRemove(src, 'stm32f20x_40x_spi.c')
	SrcRemove(src, 'spi_flash_sst25vfxx.c')

# remove no need file.
if GetDepend('RT_USING_DEVICE') == False or GetDepend('RT_USING_I2C') == False:
	SrcRemove(src, 'stm32_i2c.c')

if GetDepend('RT_USING_USB_DEVICE') == False:
	SrcRemove(src, 'stm32f4xx_dcd.c')
	SrcRemove(src, 'usb_bsp.c')

if GetDepend('RT_LWIP_PPP') == False:
	SrcRemove(src, 'uspi.c')

CPPPATH = [cwd]

group = DefineGroup('Drivers', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
